-- Inventario comercial confiable · ParaTuHogar
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.inventario_eventos (
    id bigint generated by default as identity primary key,
    producto_id text not null,
    producto_nombre text not null,
    tipo text not null check (tipo in ('nuevo', 'reposicion', 'agotado', 'precio', 'comision')),
    valor_anterior text,
    valor_nuevo text,
    datos_producto jsonb not null default '{}'::jsonb,
    ocurrido_en timestamptz not null default now(),
    confiable boolean not null default false
);

alter table public.inventario_eventos
    add column if not exists confiable boolean not null default false;

alter table public.productos
    add column if not exists inventario_actualizado_en timestamptz not null default now();

create index if not exists inventario_eventos_producto_idx
    on public.inventario_eventos (producto_id, ocurrido_en desc);
create index if not exists inventario_eventos_fecha_idx
    on public.inventario_eventos (ocurrido_en desc);

alter table public.inventario_eventos enable row level security;

drop policy if exists "inventario_eventos_lectura_publica" on public.inventario_eventos;
create policy "inventario_eventos_lectura_publica"
on public.inventario_eventos for select
to anon, authenticated
using (true);

create or replace function public.numero_comercial(valor text)
returns numeric
language plpgsql
immutable
as $$
declare
    limpio text := replace(trim(coalesce(valor, '')), ',', '.');
begin
    if limpio = '' then return null; end if;
    return limpio::numeric;
exception when invalid_text_representation or numeric_value_out_of_range then
    return null;
end;
$$;

create or replace function public.marcar_revision_inventario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op = 'INSERT'
       or upper(trim(coalesce(old.disponible::text, ''))) is distinct from upper(trim(coalesce(new.disponible::text, '')))
       or public.numero_comercial(old.precio::text) is distinct from public.numero_comercial(new.precio::text)
       or public.numero_comercial(old.comision::text) is distinct from public.numero_comercial(new.comision::text)
    then
        new.inventario_actualizado_en := now();
    end if;
    return new;
end;
$$;

drop trigger if exists productos_marcar_revision_inventario on public.productos;
create trigger productos_marcar_revision_inventario
before insert or update on public.productos
for each row execute function public.marcar_revision_inventario();

create or replace function public.registrar_evento_inventario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    anterior jsonb := case when tg_op = 'INSERT' then '{}'::jsonb else to_jsonb(old) end;
    actual jsonb := to_jsonb(new);
    producto_id_text text := coalesce(actual->>'id', actual->>'nombre');
    producto_nombre_text text := coalesce(actual->>'nombre', 'Producto');
    disponible_antes boolean := upper(coalesce(anterior->>'disponible', 'NO')) = 'SI';
    disponible_ahora boolean := upper(coalesce(actual->>'disponible', 'NO')) = 'SI';
    precio_antes numeric := public.numero_comercial(anterior->>'precio');
    precio_ahora numeric := public.numero_comercial(actual->>'precio');
    comision_antes numeric := public.numero_comercial(anterior->>'comision');
    comision_ahora numeric := public.numero_comercial(actual->>'comision');
begin
    if tg_op = 'INSERT' then
        if disponible_ahora then
            insert into public.inventario_eventos
                (producto_id, producto_nombre, tipo, valor_nuevo, datos_producto, confiable)
            values
                (producto_id_text, producto_nombre_text, 'nuevo', actual->>'disponible', actual, true);
        end if;
        insert into public.control_sistema (clave, valor)
        values ('ultimo_cambio_productos', now()::text)
        on conflict (clave) do update set valor = excluded.valor;
        return new;
    end if;

    if disponible_antes is distinct from disponible_ahora then
        insert into public.inventario_eventos
            (producto_id, producto_nombre, tipo, valor_anterior, valor_nuevo, datos_producto, confiable)
        values (
            producto_id_text,
            producto_nombre_text,
            case when disponible_ahora then 'reposicion' else 'agotado' end,
            anterior->>'disponible',
            actual->>'disponible',
            actual,
            true
        );
    end if;

    if precio_antes is not null
       and precio_ahora is not null
       and abs(precio_antes - precio_ahora) >= 0.01 then
        insert into public.inventario_eventos
            (producto_id, producto_nombre, tipo, valor_anterior, valor_nuevo, datos_producto, confiable)
        values
            (producto_id_text, producto_nombre_text, 'precio',
             precio_antes::text, precio_ahora::text, actual, true);
    end if;

    if comision_antes is not null
       and comision_ahora is not null
       and abs(comision_antes - comision_ahora) >= 0.01 then
        insert into public.inventario_eventos
            (producto_id, producto_nombre, tipo, valor_anterior, valor_nuevo, datos_producto, confiable)
        values
            (producto_id_text, producto_nombre_text, 'comision',
             comision_antes::text, comision_ahora::text, actual, true);
    end if;

    insert into public.control_sistema (clave, valor)
    values ('ultimo_cambio_productos', now()::text)
    on conflict (clave) do update set valor = excluded.valor;

    return new;
end;
$$;

drop trigger if exists productos_historial_comercial on public.productos;
create trigger productos_historial_comercial
after insert or update on public.productos
for each row execute function public.registrar_evento_inventario();

grant select on public.inventario_eventos to anon, authenticated;

-- Los eventos anteriores a esta versión permanecen como confiable = false
-- y la web no los mostrará como cambios comerciales.
