const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('es-ES',{maximumFractionDigits:2});
const pct=v=>`${(Number(v||0)*100).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
export function googleLoadingSources(previous){return Object.fromEntries(['analytics','search'].map(name=>[name,{...previous?.[name],state:'loading'}]));}
export function panelAvailability(state,tab){
  if(tab==='marketing'||state.snapshot?.loadedAt)return null;
  return `<div class="${state.loading?'loading-state':'error-state'}" role="status">${esc(state.loading?'Cargando ventas y pedidos…':state.error||'Todavía no hay una consulta de ventas completada. Pulsa Actualizar.')}</div>`;
}
export function sourceLabel(source){return ({connected:'Conectado',empty:'Conectado · sin datos en el periodo',loading:'Consultando…',error:'Error de consulta',stale:'Datos anteriores · revisar fecha'})[source?.state]||'Pendiente de consulta';}
export function renderGoogleReports(sources={}){
  const models={};
  function chart(key,title,rows,dimension,metrics,description,type='bar'){
    if(!rows?.length)return `<section class="stats-card"><h3>${esc(title)}</h3><p>Sin datos para este desglose.</p></section>`;
    const series=rows.slice(0,type==='line'?367:12);
    models[key]={type,labels:series.map(r=>r[dimension]),datasets:metrics.map(([name,label])=>({label,data:series.map(r=>Number(r[name]||0))}))};
    return `<section class="stats-card"><h3>${esc(title)}</h3><p>${esc(description)}</p><div style="height:280px;position:relative"><canvas data-chart-canvas="${key}" role="img" aria-label="${esc(title)}"></canvas></div><details class="metric-help"><summary>Explicación y datos · ${rows.length} filas</summary><p>${esc(description)}</p><div class="table-wrap"><table class="stats-table"><thead><tr><th>${esc(title)}</th>${metrics.map(([,label])=>`<th>${esc(label)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row[dimension])}</td>${metrics.map(([name])=>`<td>${num(row[name])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></section>`;
  }
  function kpi(title,value,explanation){return `<article class="kpi-card"><span class="kpi-label">${title}</span><strong class="kpi-value cyan">${value}</strong><details class="metric-help"><summary>¿Qué significa?</summary><p>${explanation}</p></details></article>`;}
  function section(name,source,render){
    const head=`<div class="section-heading"><div><h2>${name}</h2><p>${esc(sourceLabel(source))}${source?.period?` · ${esc(source.period.from)} a ${esc(source.period.to)}`:''}${source?.fetchedAt?` · Consultado ${esc(new Date(source.fetchedAt).toLocaleString('es-ES',{timeZone:'America/Havana'}))}`:''}</p></div></div>`;
    const notice=`<div class="${source?.state==='error'?'error-state':'notice'}">${esc(source?.message||'Los informes se consultan al cargar el panel o cambiar las fechas.')}</div>`;
    return `<section style="margin-top:28px">${head}${notice}${source?.reports&&['connected','stale'].includes(source.state)?render(source.reports):''}</section>`;
  }
  const html=section('Google Analytics 4',sources.analytics,r=>{
    const s=r.summary?.[0]||{};
    return `<p>Visitas medidas con consentimiento. Días y horas de La Habana. No representan todos los visitantes ni la ganancia contable.</p><div class="kpi-grid">${kpi('Usuarios activos',num(s.activeUsers),'Personas distintas activas según GA4. No se deben sumar usuarios diarios para obtener el total mensual.')}${kpi('Sesiones',num(s.sessions),'Visitas iniciadas; una persona puede abrir varias sesiones.')}${kpi('Páginas vistas',num(s.screenPageViews),'Vistas de páginas, incluidas las repetidas.')}${kpi('Tasa de interacción',pct(s.engagementRate),'Proporción de sesiones con interacción, según la definición de GA4. No es una tasa de compra.')}${kpi('Duración media',`${num(s.averageSessionDuration)} s`,'Duración media de una sesión en segundos.')}${kpi('Eventos clave',num(s.keyEvents),'Acciones configuradas como clave en Google. No equivalen a pedidos entregados ni a beneficio.')}</div><div class="chart-grid" style="margin-top:14px">${chart('googleGaDaily','Visitas por día',r.daily,'date',[['sessions','Sesiones'],['screenPageViews','Vistas']],'Evolución diaria. Los usuarios totales se consultan aparte para no duplicarlos.','line')}${chart('googleGaChannels','Canales de llegada',r.channels,'sessionDefaultChannelGroup',[['sessions','Sesiones']],'Cómo llegaron las visitas: buscadores, enlaces, redes o acceso directo.')}${chart('googleGaDevices','Dispositivos',r.devices,'deviceCategory',[['sessions','Sesiones']],'Sesiones por tipo de dispositivo.')}${chart('googleGaCountries','Países',r.countries,'country',[['sessions','Sesiones']],'País estimado por Google; no es la zona de entrega del pedido.')}${chart('googleGaPages','Páginas más vistas',r.pages,'pagePath',[['screenPageViews','Vistas']],'Rutas públicas consultadas. Rankings limitados a 1.000 filas; gráfico: primeras 12.')}${chart('googleGaHours','Horas de visita',r.hours,'hour',[['sessions','Sesiones']],'Horas del día en La Habana; son visitas, no horas de venta.','line')}</div>`;
  })+section('Google Search Console',sources.search,r=>{
    const s=r.summary?.[0]||{};
    return `<p>Solo resultados orgánicos de búsqueda web. Días del Pacífico (Google), no La Habana. Las consultas anónimas pueden no aparecer en rankings.</p><div class="kpi-grid">${kpi('Clics desde Google',num(s.clicks),'Clics que llevaron a la web desde resultados orgánicos de Google.')}${kpi('Impresiones en Google',num(s.impressions),'Veces que una página apareció en resultados de búsqueda.')}${kpi('CTR orgánico',pct(s.ctr),'Clics divididos entre impresiones del periodo. Se usa el total de Google, no el promedio de los porcentajes diarios.')}${kpi('Posición media',num(s.position),'Posición media comunicada por Google. Un número menor suele indicar mejor ubicación; no es una posición fija.')}</div><div class="chart-grid" style="margin-top:14px">${chart('googleSearchDaily','Clics por día',r.daily,'date',[['clicks','Clics']],'Clics diarios desde Google; datos finales disponibles con retraso.','line')}${chart('googleSearchImpressions','Visibilidad por día',r.daily,'date',[['impressions','Impresiones']],'Impresiones diarias; no se mezclan con vistas internas de la tienda.','line')}${chart('googleSearchQueries','Qué buscan tus clientes',r.queries,'query',[['clicks','Clics']],'Consultas con más clics. Detalles sujetos a privacidad y límite de 1.000 filas.')}${chart('googleSearchPages','Páginas que atraen visitas',r.pages,'page',[['clicks','Clics']],'Páginas de destino que reciben clics orgánicos.')}${chart('googleSearchDevices','Dispositivos en búsquedas',r.devices,'device',[['clicks','Clics']],'Tipo de dispositivo desde el que se buscó.')}${chart('googleSearchCountries','Países en búsquedas',r.countries,'country',[['clicks','Clics']],'País del buscador, no la dirección del cliente.')}</div>`;
  });
  return {html,chartModels:models};
}
