import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {createHandler,hash} from '../supabase/functions/secure-data/handler.mjs';
const source=fs.readFileSync(new URL('../js/storefront.js',import.meta.url),'utf8');
const functions=source.slice(source.indexOf('let crmClients = [];'),source.indexOf('// 3. SISTEMA DE AUTO-GUARDADO'));
const profiles=[{id:'p',nombre:'Parent',rol:'gestor'},{id:'s',nombre:'Child',parent_id:'p'},{id:'sibling',nombre:'Sibling',parent_id:'p'},{id:'other',nombre:'Other'},{id:'admin',nombre:'Admin',rol:'admin'}].map(p=>({...p,estado:'activo',activo:true,password:'synthetic-password'}));
async function fixture(actor){
 const token='a'.repeat(64),orders=profiles.map(p=>({cliente:'Synthetic '+p.id,ci:'synthetic-ci',telefono:'5000000'+profiles.indexOf(p),direccion:'Synthetic street',gestor:p.parent_id?'Parent':p.nombre,subgestor_nombre:p.parent_id?p.nombre:null}));
 const rows={gestores:profiles,pth_secure_sessions:[{token_hash:await hash(token),gestor_id:actor.id,credential_hash:await hash('synthetic-password'),expires_at:'2099-01-01'}],pedidos:orders},trace=[];
 class Query{constructor(table){this.table=table;this.filters=[];}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}gt(k,v){this.filters.push([k,v,'gt']);return this;}order(){return this;}limit(){return this;}maybeSingle(){this.single=true;return this;}then(resolve,reject){return Promise.resolve().then(()=>{trace.push([this.table,this.filters]);const data=rows[this.table].filter(r=>this.filters.every(([k,v,op])=>op==='gt'?r[k]>v:r[k]===v));return{data:this.single?data[0]||null:data,error:null};}).then(resolve,reject);}}
 const handler=createHandler({db:{from:table=>new Query(table)}});
 const adapter={from(table){const body={action:'query',table,op:'select',filters:[],orders:[]};return{select(columns){body.columns=columns;return this;},order(column,options){body.orders.push({column,...options});return this;},limit(limit){body.limit=limit;return this;},eq(column,value){body.filters.push({method:'eq',column,value});return this;},async then(resolve,reject){try{const response=await handler(new Request('https://synthetic.test',{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify(body)}));resolve(await response.json());}catch(e){reject(e);}}};}};
 const context={window:{addEventListener(){},currentUserData:actor,gestorName:actor.nombre,isAdmin:false,PTHSecureData:{accountId:()=>actor.id,token:()=>token}},offlineStorefront:{current:()=>null},supabaseClient:adapter,console:{log(){}},document:{getElementById:()=>null}};
 vm.runInNewContext(functions,context);await context.loadClientCRM();return{clients:JSON.parse(vm.runInNewContext('JSON.stringify(crmClients)',context)),trace};
}
for(const actor of profiles.filter(p=>p.rol!=='admin'))test('normal CRM retains mandatory gateway scope for '+actor.id,async()=>{const {clients,trace}=await fixture(actor);const expected=actor.id==='p'?['Synthetic p','Synthetic s','Synthetic sibling']:['Synthetic '+actor.id];assert.deepEqual(clients.map(c=>c.cliente),expected);assert.ok(trace.some(([table,filters])=>table==='pedidos'&&filters.some(([k,v])=>k===(actor.parent_id?'subgestor_nombre':'gestor')&&v===actor.nombre)));});

test('administrator browsing as seller retains its narrow frontend CRM filter',async()=>{const actor=profiles.find(p=>p.id==='admin');const {clients}=await fixture(actor);assert.deepEqual(clients.map(c=>c.cliente),['Synthetic admin']);});

function delayedCRM(){
 let owner='a',token='token-a';const pending=[],events={},rendered=[];
 const context={window:{gestorName:'Synthetic A',isAdmin:false,currentUserData:{id:'a'},addEventListener:(name,fn)=>events[name]=fn,PTHSecureData:{accountId:()=>owner,token:()=>token}},offlineStorefront:{current:()=>null},document:{getElementById:()=>null},console:{log(){}},supabaseClient:{from(){return{select(){return this},order(){return this},limit(){return this},eq(){return this},then(resolve){pending.push(resolve);}};}}};
 vm.runInNewContext(functions,context);context.renderCheckoutClientChoices=()=>rendered.push(JSON.parse(vm.runInNewContext('JSON.stringify(crmClients)',context)));
 return{context,pending,rendered,change(){owner='b';token='token-b';context.window.gestorName='Synthetic B';context.window.currentUserData={id:'b'};events['pth:session-changed']?.();},clients:()=>JSON.parse(vm.runInNewContext('JSON.stringify(crmClients)',context))};
}
const customer=label=>({cliente:label,telefono:'50001111',ci:'synthetic-ci',direccion:'Synthetic address'});
test('a late CRM response cannot restore previous-account choices',async()=>{const f=delayedCRM(),load=f.context.loadClientCRM();await Promise.resolve();f.change();f.pending[0]({data:[customer('Old account')],error:null});await load;assert.deepEqual(f.clients(),[]);assert.equal(f.rendered.some(rows=>rows.some(row=>row.cliente==='Old account')),false);});
test('an older same-account CRM refresh cannot replace newer choices',async()=>{const f=delayedCRM(),first=f.context.loadClientCRM();await Promise.resolve();const second=f.context.loadClientCRM();await Promise.resolve();f.pending[1]({data:[customer('Latest')],error:null});await second;f.pending[0]({data:[customer('Stale')],error:null});await first;assert.equal(f.clients()[0].cliente,'Latest');});
test('failed CRM refresh leaves no old selectable client',async()=>{const f=delayedCRM(),first=f.context.loadClientCRM();await Promise.resolve();f.pending[0]({data:[customer('Old')],error:null});await first;const second=f.context.loadClientCRM();await Promise.resolve();assert.deepEqual(f.clients(),[]);f.pending[1]({data:null,error:{message:'Synthetic outage'}});await second;assert.deepEqual(f.clients(),[]);});
