const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const shared=require('../js/checkout-form-shared.js');
const zones=['Centro Habana','Plaza de la Revolución','Playa','Cotorro','Habana del Este'];
const tariffs=zones.map(municipio=>({municipio,localidad:'Centro',precio_pequeno:7,precio_grande:17}));
// Compare the shared rule to the actual existing checkout, rather than a mirrored expectation.
const source=fs.readFileSync(require.resolve('../js/storefront.js'),'utf8'),start=source.indexOf('window.obtenerCostoMensajeriaGlobal = function()'),end=source.indexOf('\n};',start)+3;
function original(lines,municipio,pickup=false){const scope={window:{},cart:lines,newCheckoutShippingOverride:null,tarifasMensajeria:shared.tariffMap(tariffs),carritoTieneEquipoGrande:()=>lines.some(p=>p.tamaño_envio==='Grande'),document:{getElementById:id=>({value:id==='check-municipio'?municipio:'Centro',checked:pickup})}};vm.runInNewContext(source.slice(start,end),scope);return scope.window.obtenerCostoMensajeriaGlobal();}
test('all existing delivery rules match normal checkout for 65 combinations',()=>{let compared=0;for(const municipio of zones)for(const qty of [1,3,4])for(const product of [{nombre:'Equipo',proveedor:'B'},{nombre:'Equipo',proveedor:'A'},{nombre:'Aspiradora',proveedor:'Proveedor A'},{nombre:'Equipo grande',proveedor:'A',tamaño_envio:'Grande'}]){const lines=[{...product,qty,precio_venta:80}];assert.equal(shared.shipping({lines,municipio,localidad:'Centro',tariffs}),original(lines,municipio));compared++;}assert.equal(compared,60);for(const municipio of zones)assert.equal(shared.shipping({lines:[{qty:4}],municipio,localidad:'Centro',pickup:true,tariffs}),original([{qty:4}],municipio,true));});
test('missing, invalid or prototype-named delivery rates never become free',()=>{for(const municipio of ['', 'Unknown','__proto__'])assert.equal(shared.shipping({lines:[{qty:1}],municipio,localidad:'Centro',tariffs}),null);assert.equal(shared.shipping({lines:[],municipio:'A',localidad:'B',tariffs:[{municipio:'A',localidad:'B',precio_pequeno:-1,precio_grande:1}]}),null);const map=shared.tariffMap([{municipio:'__proto__',localidad:'constructor',precio_pequeno:3,precio_grande:6}]);assert.equal(shared.shipping({lines:[{qty:1}],municipio:'__proto__',localidad:'constructor',tariffs:map}),3);assert.equal({}.pq,undefined);});
test('account prices and quantities determine equipment total; no invented currency conversion',()=>{assert.deepEqual(shared.estimate({lines:[{qty:2,price:120},{qty:1,precio_venta:90}],municipio:'Centro Habana',localidad:'Centro',tariffs}),{equipment:330,shipping:7,total:337});assert.deepEqual(shared.estimate({lines:[{qty:2,price:120}],tariffs}),{equipment:240,shipping:null,total:null});});
test('manual clipboard parser keeps customer input plain text',()=>{const result=shared.parseClipboard('Nombre: Juan Pérez\nCI: 90010112345\nTeléfono: +53 51234567\nDirección: Calle 23 #4');assert.equal(result.ci,'90010112345');assert.equal(result.tel,'51234567');assert.match(result.dir,/Calle 23/);assert.match(shared.parseClipboard('<img src=x onerror=alert(1)>').nombre,/<img/i);});

test('B2B category detection matches the normal pickup-only rule',()=>{for(const category of ['MAYORISTA','Lotes B2B','Mipyme · equipos'])assert.equal(shared.isWholesale({categoria:category}),true);assert.equal(shared.isWholesale({categoria:'HOGAR'}),false);});
