const test=require('node:test'),assert=require('node:assert/strict');
const api=require('../js/offline-checkout-copy.js');
const now=1700000000000;
const data=()=>({products:[{id:'p1',nombre:'Equipo',precio:90,disponible:'SI',categoria:'HOGAR',proveedor:'A',tamaño_envio:'Grande',password:'secret',comision:20}],clients:[{cliente:'Client A',ci:'123',telefono:'50000000',direccion:'Calle A',gestor:'Unrelated',token:'secret'}],tariffs:[{municipio:'Centro Habana',localidad:'Centro',precio_pequeno:6,precio_grande:10,password:'secret'}]});
const memory=()=>{const rows=new Map();return {rows,async update(owner,fn){const result=fn(rows.get(owner)||null);if(result===null)rows.delete(owner);else rows.set(owner,structuredClone(result));return structuredClone(result);}};};
const storage=profile=>{const rows=new Map([['pth_session',JSON.stringify({data:profile})],['pth_secure_token','a'.repeat(64)]]);return {getItem:key=>rows.get(key)||null,setItem:(key,value)=>rows.set(key,value),removeItem:key=>rows.delete(key)};};
test('copy requires explicit consent, reliable session expiry and a stable account',async()=>{const store=memory(),copies=api.create(null,{store,now:()=>now});await assert.rejects(copies.save('a',data(),{profile:{id:'a'},sessionUntil:now+1000}),{code:'CONSENT'});await assert.rejects(copies.save('a',data(),{profile:{id:'a'},consent:true}),{code:'SESSION_EXPIRED'});await assert.rejects(copies.save('a',data(),{profile:{id:'a'},consent:true,sessionUntil:now+1000,guard:()=>false}),{code:'ACCOUNT'});assert.equal(store.rows.size,0);});
test('private whitelist, per-account visibility and session expiry purge',async()=>{const store=memory();let time=now;const copies=api.create(null,{store,now:()=>time});const saved=await copies.save('a',data(),{profile:{id:'a'},consent:true,sessionUntil:now+1000});assert.doesNotMatch(JSON.stringify(saved),/secret|comision|gestor|password|token/);assert.equal((await copies.read('a',{profile:{id:'a'}})).products[0].tamaño_envio,'Grande');assert.equal(await copies.read('b',{profile:{id:'b'}}),null);time+=1000;assert.equal(await copies.read('a',{profile:{id:'a'}}),null);assert.equal(store.rows.size,0);});
test('7 days maximum, corrupted copy removed, quota never claims save',async()=>{const store=memory(),copies=api.create(null,{store,now:()=>now});const saved=await copies.save('a',data(),{profile:{id:'a'},consent:true,sessionUntil:now+20*86400000});assert.equal(saved.expiresAt,now+api.AGE);store.rows.get('a').products[0].precio=-1;assert.equal(await copies.read('a',{profile:{id:'a'}}),null);const refused=api.create(null,{store:{update:async()=>{throw Object.assign(Error('quota'),{code:'STORAGE'});}},now:()=>now});await assert.rejects(refused.save('a',data(),{profile:{id:'a'},consent:true,sessionUntil:now+1000}),{code:'STORAGE'});});
for(const profile of [{id:'admin',nombre:'Own Admin',rol:'superadmin'},{id:'a',nombre:'Own Sales',rol:'gestor'},{id:'child',nombre:'Own Child',parent_id:'parent'}])test('capture queries own sales even privileged: '+profile.id,async()=>{const calls=[],local=storage(profile),query={then:resolve=>resolve({data:data().clients,error:null})};for(const name of ['select','eq','order','limit','forSession'])query[name]=(...args)=>{calls.push([name,...args]);return query;};const client={from:table=>{calls.push(['from',table]);if(table==='gestores'){const names={then:resolve=>resolve({data:[{id:profile.id,nombre:profile.nombre}],error:null})};for(const name of ['select','eq','limit','forSession'])names[name]=(...args)=>{calls.push(['names:'+name,...args]);return names;};return names;}return query;}};const result=await api.capture({client,profile,products:data().products,tariffs:data().tariffs,storage:local,token:'a'.repeat(64),sessionUntil:Date.now()+1000});assert.deepEqual(calls.find(c=>c[0]==='eq'),['eq',profile.parent_id?'subgestor_nombre':'gestor',profile.nombre]);assert.deepEqual(calls.find(c=>c[0]==='select'),['select','cliente, ci, telefono, direccion']);assert.equal(result.clients.length,1);});
test('capture refreshes server session and refuses a late account change',async()=>{const profile={id:'a',nombre:'Own'},local=storage(profile);let resolve;const response=new Promise(done=>resolve=done);const query={then:(yes,no)=>response.then(yes,no)};for(const name of ['select','eq','order','limit','forSession'])query[name]=()=>query;const capture=api.capture({client:{from:()=>query},profile,products:data().products,tariffs:data().tariffs,storage:local,token:'a'.repeat(64),secureData:{refresh:async()=>profile,expiresAt:()=>Date.now()+10000}});await new Promise(done=>setImmediate(done));local.setItem('pth_session',JSON.stringify({data:{id:'b'}}));resolve({data:data().clients,error:null});await assert.rejects(capture,{code:'ACCOUNT'});});
test('lifecycle purges on logout, expiry and account/session change',async()=>{for(const mode of ['logout','expired','account','token','role']){const profile={id:'a'},local=storage(profile),listeners={},cleared=[];api.bindLifecycle({addEventListener:(name,fn)=>listeners[name]=fn},local,{clear:async owner=>cleared.push(owner)});if(mode==='account')local.setItem('pth_session',JSON.stringify({data:{id:'b'}}));if(mode==='token')local.setItem('pth_secure_token','new');listeners['pth:session-changed']({reason:mode,type:'pth:session-changed'});assert.deepEqual(cleared,['a']);}});

test('ambiguous administrator names never copy a global customer agenda',async()=>{const profile={id:'admin',nombre:'Shared Name',rol:'superadmin'},local=storage(profile);let orders=0;const q={then:resolve=>resolve({data:[{id:'admin'},{id:'other'}],error:null})};for(const name of ['select','eq','limit','forSession'])q[name]=()=>q;await assert.rejects(api.capture({client:{from:table=>{if(table==='pedidos')orders++;return q;}},profile,products:data().products,tariffs:data().tariffs,storage:local,token:'a'.repeat(64),sessionUntil:Date.now()+1000}),{code:'CLIENT_SCOPE_AMBIGUOUS'});assert.equal(orders,0);});

test('a reopened copy is erased when name, role or parent scope changed while closed',async()=>{for(const change of [{rol:'gestor'},{nombre:'Renamed'},{parent_id:'parent'}]){const store=memory(),copies=api.create(null,{store,now:()=>now}),profile={id:'a',nombre:'Own',rol:'superadmin'};await copies.save('a',data(),{profile,consent:true,sessionUntil:now+1000});assert.equal(await copies.read('a',{profile:{...profile,...change}}),null);assert.equal(store.rows.size,0);}});

test('normal catalogue display fields survive; signed/private media and credentials do not',()=>{const value=data();Object.assign(value.products[0],{thumbnail:'img_productos/equipo.jpg',image1:'https://images.example/equipo.webp',image2:'https://project.example/storage/v1/object/sign/private/customer.png?token=private',image3:'javascript:alert(1)',garantia:'1 año',descripcion:'Detalles públicos',precio_flexible:true});const product=api.clean(value).products[0];assert.equal(product.thumbnail,'img_productos/equipo.jpg');assert.equal(product.image1,'https://images.example/equipo.webp');assert.equal(product.image2,'');assert.equal(product.image3,'');assert.equal(product.garantia,'1 año');assert.equal(product.descripcion,'Detalles públicos');assert.equal(product.precio_flexible,true);});
test('scope changes during a delayed write cannot re-save a revoked device copy',async()=>{const local=storage({id:'a',nombre:'Own',rol:'superadmin'});const copies=api.create(null,{now:()=>now,store:{async update(owner,fn){local.setItem('pth_session',JSON.stringify({data:{id:'a',nombre:'Own',rol:'gestor',parent_id:'parent'}}));return fn(null);}}});await assert.rejects(copies.save('a',data(),{profile:{id:'a',nombre:'Own',rol:'superadmin'},storage:local,consent:true,sessionUntil:now+1000}),{code:'ACCOUNT'});});
