const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../js/offline-storefront-adapter.js');
const profile={id:'account-a',nombre:'Ana',rol:'gestor',estado:'activo',password:'__session__'};
function fixture(){
 let token='a'.repeat(64),savedProfile=profile,expiry=5000,adopted=0,read=0,cleared=0;
 const listeners={},root={navigator:{onLine:false},addEventListener:(name,fn)=>listeners[name]=fn};
 const secureData={token:()=>token,expiresAt:()=>expiry,offlineProfile:()=>savedProfile,adoptOfflineProfile:()=>{adopted++;return savedProfile;},refresh:async()=>savedProfile};
 const copy={owner:profile.id,savedAt:1000,expiresAt:5000,products:[{id:'p',nombre:'Equipo',precio:10}],clients:[{cliente:'Cliente propio'}],tariffs:[{municipio:'M',localidad:'L',precio_pequeno:6,precio_grande:10}]};
 const copies={read:async(owner,{profile:actor})=>{read++;return owner===profile.id&&actor===profile?copy:null;}};
 const api=create({root,secureData,copies,publicCopy:()=>({savedAt:1000,products:[{id:'public',nombre:'Público',precio:10}]}),now:()=>2000,onClear:()=>cleared++});
 return {api,root,listeners,copy,secureData,get adopted(){return adopted;},get read(){return read;},get cleared(){return cleared;},setToken:value=>token=value,setProfile:value=>savedProfile=value,setExpiry:value=>expiry=value};
}
test('adopts display identity only after a scoped saved copy is read',async()=>{const f=fixture();assert.equal(f.adopted,0);assert.equal((await f.api.fallback()).owner,profile.id);assert.equal(f.read,1);assert.equal(f.adopted,1);assert.equal(f.api.usingCopy(),true);assert.equal(Object.hasOwn(f.api.current(),'token'),false);});
test('network failure permits saved display; denial and session changes never do',async()=>{for(const error of [{status:401,code:'NETWORK_ERROR'},{status:403,code:'NETWORK_ERROR'},{code:'SESSION_CHANGED'},{code:'SESSION_EXPIRED'},{code:'FORBIDDEN'}]){const f=fixture();assert.equal(await f.api.fallback(error),null);assert.equal(f.adopted,0);}const f=fixture();f.root.navigator.onLine=true;assert.equal(await f.api.fallback({code:'VALIDATION'}),null);assert.ok(await f.api.fallback({code:'NETWORK_ERROR'}));});
test('a live denial removes an already rendered private copy',async()=>{const f=fixture();await f.api.fallback();assert.equal(await f.api.fallback({status:403}),null);assert.equal(f.api.current(),null);assert.equal(f.cleared,1);});
test('signed-in device with no valid own copy never uses public contacts/catalogue',async()=>{const f=fixture();f.setProfile({...profile,id:'account-b'});assert.equal(await f.api.fallback(),null);f.setProfile(null);assert.equal(await f.api.fallback(),null);});
test('an interrupted read cannot adopt another account',async()=>{const f=fixture();let resolve;const promise=new Promise(r=>resolve=r);const api=create({root:f.root,secureData:f.secureData,copies:{read:()=>promise},now:()=>2000});const pending=api.fallback();f.setToken('b'.repeat(64));f.setProfile({...profile,id:'b'});resolve(f.copy);assert.equal(await pending,null);assert.equal(f.adopted,0);});
test('logout, role change and session expiry immediately clear private display',async()=>{for(const change of [f=>f.setToken(null),f=>f.setProfile({...profile,rol:'admin'}),f=>f.setExpiry(1999)]){const f=fixture();await f.api.fallback();change(f);assert.equal(f.api.current(),null);assert.equal(f.cleared,1);}const f=fixture();await f.api.fallback();f.listeners['pth:session-changed']();assert.equal(f.api.current(),null);assert.equal(f.cleared,1);});
test('expiry may emit session change while checking a copy without a race or stale DOM',async()=>{const f=fixture();await f.api.fallback();f.secureData.offlineProfile=()=>{f.listeners['pth:session-changed']();return null;};assert.equal(f.api.usingCopy(),false);assert.equal(f.cleared,1);});
test('anonymous visitors get only public products and no client/tariff copy',async()=>{const f=fixture();f.setToken(null);f.setProfile(null);const copy=await f.api.fallback();assert.equal(copy.owner,null);assert.deepEqual(copy.clients,[]);assert.deepEqual(copy.tariffs,[]);assert.equal(copy.products[0].id,'public');});
test('reconnect verifies live session before reload and preserves copy on failure',async()=>{const f=fixture();await f.api.fallback();f.root.navigator.onLine=true;let refresh=0,reload=0;f.secureData.refresh=async()=>{refresh++;throw Error('offline');};assert.equal(await f.api.reconnect(async()=>reload++),false);assert.equal(reload,0);assert.equal(f.api.usingCopy(),true);f.secureData.refresh=async()=>{refresh++;return profile;};assert.equal(await f.api.reconnect(async()=>{reload++;f.api.live();}),true);assert.equal(refresh,2);assert.equal(reload,1);assert.equal(f.api.usingCopy(),false);});
