begin;

create table if not exists public.liquidaciones_sistema (
  id uuid primary key default gen_random_uuid(),
  total numeric(12,2) not null check (total >= 0),
  pedidos_count integer not null check (pedidos_count >= 0),
  lineas_count integer not null check (lineas_count >= 0),
  admin_id uuid null,
  admin_nombre text not null,
  referencia text null,
  creado_en timestamptz not null default now()
);

create table if not exists public.deuda_sistema_detalle (
  id bigint generated by default as identity primary key,
  pedido_id uuid not null references public.pedidos(id) on delete restrict,
  linea integer not null check (linea > 0),
  orden_dia text,
  fecha_pedido timestamptz,
  producto text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2),
  tarifa_unitaria numeric(12,2),
  tarifa_total numeric(12,2),
  estado text not null default 'pendiente' check (estado in ('pendiente','liquidado','incidencia')),
  incidencia text,
  liquidacion_id uuid null references public.liquidaciones_sistema(id) on delete restrict,
  calculado_en timestamptz not null default now(),
  liquidado_en timestamptz,
  unique (pedido_id, linea)
);

create table if not exists public.liquidaciones_sistema_detalle (
  liquidacion_id uuid not null references public.liquidaciones_sistema(id) on delete restrict,
  deuda_detalle_id bigint not null references public.deuda_sistema_detalle(id) on delete restrict,
  pedido_id uuid not null references public.pedidos(id) on delete restrict,
  tarifa_total numeric(12,2) not null,
  primary key (liquidacion_id, deuda_detalle_id),
  unique (deuda_detalle_id)
);

create index if not exists deuda_sistema_estado_idx
  on public.deuda_sistema_detalle(estado, fecha_pedido);

alter table public.liquidaciones_sistema enable row level security;
alter table public.deuda_sistema_detalle enable row level security;
alter table public.liquidaciones_sistema_detalle enable row level security;

revoke all on public.liquidaciones_sistema from anon, authenticated;
revoke all on public.deuda_sistema_detalle from anon, authenticated;
revoke all on public.liquidaciones_sistema_detalle from anon, authenticated;

create or replace function public.tarifa_sistema_por_unidad(p_precio numeric)
returns numeric
language sql
immutable
strict
set search_path = public, pg_temp
as $function$
  select case
    when p_precio <= 60 then 0.50
    when p_precio <= 150 then 1.00
    when p_precio <= 399 then 2.00
    when p_precio <= 999 then 3.00
    else 5.00
  end::numeric(12,2);
$function$;

create or replace function public.materializar_deuda_sistema_pedido(p_pedido_id uuid)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_pedido public.pedidos%rowtype;
  v_lineas integer := 0;
  v_catalogo_total numeric := 0;
  v_neto numeric := 0;
  v_precio_unit numeric;
  v_tarifa_unit numeric;
  v_incidencia text;
  v_formato_invalido boolean := false;
  r record;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then return 0; end if;
  perform pg_advisory_xact_lock(hashtext('pth_liquidar_deuda_sistema'));
  if v_pedido.estado <> 'Entregado' then return 0; end if;
  if coalesce(lower(trim(v_pedido.pago_sistema)), 'pendiente') = 'pagado' then return 0; end if;

  if exists (select 1 from public.deuda_sistema_detalle where pedido_id = p_pedido_id) then
    return 0;
  end if;

  create temporary table if not exists pg_temp.pth_deuda_lineas (
    linea integer,
    cantidad integer,
    producto text,
    precio_catalogo numeric
  ) on commit drop;
  truncate pg_temp.pth_deuda_lineas;

  insert into pg_temp.pth_deuda_lineas(linea,cantidad,producto,precio_catalogo)
  select
    s.ord::integer,
    greatest(1, (q.m)[1]::integer),
    n.nombre,
    pr.precio::numeric
  from regexp_split_to_table(
    coalesce(v_pedido.producto,''),
    '\][[:space:]]*\+[[:space:]]*'
  ) with ordinality as s(segment,ord)
  cross join lateral (
    select regexp_match(s.segment, '^\s*([0-9]+)x\s+', 'i') m
  ) q
  cross join lateral (
    select trim(regexp_replace(
      regexp_replace(s.segment, '^\s*[0-9]+x\s+', '', 'i'),
      '\s*\[(USD|CUP)\]?\s*$', '', 'i'
    )) nombre
  ) n
  left join lateral (
    select p.precio
    from public.productos p
    where lower(regexp_replace(trim(p.nombre), '[[:space:]]+', ' ', 'g')) =
          lower(regexp_replace(n.nombre, '[[:space:]]+', ' ', 'g'))
    order by
      case when lower(trim(coalesce(p.proveedor,''))) = lower(trim(coalesce(v_pedido.proveedor,''))) then 0 else 1 end,
      case when upper(coalesce(p.disponible,'')) = 'SI' then 0 else 1 end
    limit 1
  ) pr on true
  where q.m is not null;

  if not exists (select 1 from pg_temp.pth_deuda_lineas) then
    v_formato_invalido := true;
    insert into pg_temp.pth_deuda_lineas(linea,cantidad,producto,precio_catalogo)
    values (
      1,
      greatest(1, coalesce((regexp_match(coalesce(v_pedido.producto,''), '^\s*([0-9]+)x', 'i'))[1]::integer,1)),
      trim(regexp_replace(coalesce(v_pedido.producto,'Producto sin nombre'), '^\s*[0-9]+x\s*|\s*\[[^]]+\]\s*$', '', 'gi')),
      null
    );
  end if;

  select count(*), coalesce(sum(precio_catalogo * cantidad),0)
    into v_lineas, v_catalogo_total
    from pg_temp.pth_deuda_lineas;
  v_neto := coalesce(v_pedido.total,0) - coalesce(v_pedido.costo_mensajeria,0);

  for r in select * from pg_temp.pth_deuda_lineas order by linea loop
    v_incidencia := null;
    if trim(coalesce(v_pedido.producto,'')) = '' then
      v_precio_unit := null;
      v_incidencia := 'Pedido sin producto analizable';
    elsif v_formato_invalido then
      v_precio_unit := null;
      v_incidencia := 'Formato de producto no analizable';
    elsif v_lineas = 1 then
      v_precio_unit := round(v_neto / greatest(r.cantidad,1), 2);
    elsif r.precio_catalogo is null or v_catalogo_total <= 0 then
      v_precio_unit := null;
      v_incidencia := 'Producto de pedido mixto no encontrado en catálogo';
    else
      v_precio_unit := round((v_neto * (r.precio_catalogo * r.cantidad) / v_catalogo_total) / r.cantidad, 2);
    end if;

    if v_precio_unit is null or v_precio_unit < 0 then
      v_tarifa_unit := null;
      v_incidencia := coalesce(v_incidencia,'Precio unitario inválido');
    else
      v_tarifa_unit := public.tarifa_sistema_por_unidad(v_precio_unit);
    end if;

    insert into public.deuda_sistema_detalle(
      pedido_id,linea,orden_dia,fecha_pedido,producto,cantidad,
      precio_unitario,tarifa_unitaria,tarifa_total,estado,incidencia
    ) values (
      v_pedido.id,r.linea,v_pedido.orden_dia,v_pedido.fecha,r.producto,r.cantidad,
      v_precio_unit,v_tarifa_unit,
      case when v_tarifa_unit is null then null else round(v_tarifa_unit*r.cantidad,2) end,
      case when v_incidencia is null then 'pendiente' else 'incidencia' end,
      v_incidencia
    ) on conflict (pedido_id,linea) do nothing;
  end loop;

  return v_lineas;
end;
$function$;

create or replace function public.trigger_materializar_deuda_sistema()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  perform pg_advisory_xact_lock(hashtext('pth_liquidar_deuda_sistema'));

  if old.estado = 'Entregado' and new.estado <> 'Entregado' then
    delete from public.deuda_sistema_detalle
    where pedido_id=new.id and estado in ('pendiente','incidencia') and liquidacion_id is null;
    return new;
  end if;

  if new.estado = 'Entregado' and (
    old.estado is distinct from 'Entregado'
    or old.total is distinct from new.total
    or old.costo_mensajeria is distinct from new.costo_mensajeria
    or old.producto is distinct from new.producto
  ) then
    delete from public.deuda_sistema_detalle
    where pedido_id=new.id and estado in ('pendiente','incidencia') and liquidacion_id is null;
    perform public.materializar_deuda_sistema_pedido(new.id);
  end if;
  return new;
end;
$function$;

drop trigger if exists a_materializar_deuda_sistema on public.pedidos;
create trigger a_materializar_deuda_sistema
after update of estado, total, costo_mensajeria, producto on public.pedidos
for each row execute function public.trigger_materializar_deuda_sistema();

create or replace function public.reconstruir_deuda_sistema_pendiente()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  r record;
  v_total integer := 0;
begin
  for r in
    select p.id from public.pedidos p
    where p.estado = 'Entregado'
      and coalesce(lower(trim(p.pago_sistema)), 'pendiente') <> 'pagado'
    order by p.fecha, p.id
  loop
    v_total := v_total + public.materializar_deuda_sistema_pedido(r.id);
  end loop;
  return v_total;
end;
$function$;

create or replace function public.listar_deuda_sistema(p_admin_id uuid, p_password text)
returns table(
  detalle_id bigint,
  pedido_id uuid,
  linea integer,
  orden_dia text,
  fecha_pedido timestamptz,
  producto text,
  cantidad integer,
  precio_unitario numeric,
  tarifa_unitaria numeric,
  tarifa_total numeric,
  estado text,
  incidencia text
)
language plpgsql
security definer
stable
set search_path = public, pg_temp
as $function$
begin
  if not public.es_admin_boveda(p_admin_id,p_password) then
    raise exception 'Acceso reservado a administradores de la Bóveda';
  end if;
  return query
  select d.id,d.pedido_id,d.linea,d.orden_dia,d.fecha_pedido,d.producto,
         d.cantidad,d.precio_unitario,d.tarifa_unitaria,d.tarifa_total,d.estado,d.incidencia
  from public.deuda_sistema_detalle d
  where d.estado in ('pendiente','incidencia')
  order by d.fecha_pedido,d.orden_dia,d.linea;
end;
$function$;

create or replace function public.resumen_deuda_sistema(p_admin_id uuid, p_password text)
returns table(pedidos integer, lineas integer, incidencias integer, total numeric)
language plpgsql
security definer
stable
set search_path = public, pg_temp
as $function$
begin
  if not public.es_admin_boveda(p_admin_id,p_password) then
    raise exception 'Acceso reservado a administradores de la Bóveda';
  end if;
  return query
  select
    count(distinct d.pedido_id) filter (where d.estado='pendiente')::integer,
    count(*) filter (where d.estado='pendiente')::integer,
    count(*) filter (where d.estado='incidencia')::integer,
    coalesce(sum(d.tarifa_total) filter (where d.estado='pendiente'),0)::numeric(12,2)
  from public.deuda_sistema_detalle d
  where d.estado in ('pendiente','incidencia');
end;
$function$;

create or replace function public.validar_deuda_sistema_integridad()
returns jsonb
language plpgsql
security definer
stable
set search_path = public, pg_temp
as $function$
declare
  v_faltantes integer;
  v_no_entregados integer;
  v_incidencias integer;
  v_pedidos integer;
  v_lineas integer;
  v_total numeric(12,2);
  v_control numeric(12,2);
begin
  select count(*) into v_faltantes
  from public.pedidos p
  where p.estado='Entregado'
    and coalesce(lower(trim(p.pago_sistema)),'pendiente') <> 'pagado'
    and not exists (
      select 1 from public.deuda_sistema_detalle d
      where d.pedido_id=p.id and d.estado in ('pendiente','incidencia')
    );

  select count(*) into v_no_entregados
  from public.deuda_sistema_detalle d
  join public.pedidos p on p.id=d.pedido_id
  where d.estado in ('pendiente','incidencia') and p.estado <> 'Entregado';

  select
    count(distinct pedido_id) filter (where estado='pendiente'),
    count(*) filter (where estado='pendiente'),
    count(*) filter (where estado='incidencia'),
    coalesce(sum(tarifa_total) filter (where estado='pendiente'),0)
  into v_pedidos,v_lineas,v_incidencias,v_total
  from public.deuda_sistema_detalle
  where estado in ('pendiente','incidencia');

  if v_faltantes > 0 or v_no_entregados > 0 or v_incidencias > 0 then
    raise exception 'Integridad de deuda inválida: faltantes %, no entregados %, incidencias %',
      v_faltantes,v_no_entregados,v_incidencias;
  end if;

  if exists (
    select 1 from public.pedidos p join public.deuda_sistema_detalle d on d.pedido_id=p.id
    where p.orden_dia='CA-1247' and d.estado='pendiente'
  ) then
    select sum(d.tarifa_total) into v_control
    from public.deuda_sistema_detalle d join public.pedidos p on p.id=d.pedido_id
    where p.orden_dia='CA-1247' and d.estado='pendiente';
    if v_control <> 3.00 then raise exception 'Control CA-1247 inválido: %',v_control; end if;
  end if;
  if exists (
    select 1 from public.pedidos p join public.deuda_sistema_detalle d on d.pedido_id=p.id
    where p.orden_dia='CA-1324' and d.estado='pendiente'
  ) then
    select sum(d.tarifa_total) into v_control
    from public.deuda_sistema_detalle d join public.pedidos p on p.id=d.pedido_id
    where p.orden_dia='CA-1324' and d.estado='pendiente';
    if v_control <> 1.00 then raise exception 'Control CA-1324 inválido: %',v_control; end if;
  end if;

  return jsonb_build_object('pedidos',v_pedidos,'lineas',v_lineas,'incidencias',v_incidencias,'total',v_total);
end;
$function$;

create or replace function public.liquidar_deuda_sistema(
  p_admin_id uuid,
  p_password text,
  p_referencia text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_id uuid;
  v_total numeric(12,2);
  v_pedidos integer;
  v_lineas integer;
  v_admin text;
begin
  if not public.es_admin_boveda(p_admin_id,p_password) then
    raise exception 'Acceso reservado a administradores de la Bóveda';
  end if;

  -- Respeta el mismo orden de bloqueos que el trigger: primero pedidos y
  -- después el advisory lock. Evita un ciclo pedido -> advisory / advisory -> pedido.
  perform 1
    from public.pedidos p
   where exists (
     select 1 from public.deuda_sistema_detalle d
      where d.pedido_id=p.id and d.estado='pendiente'
   )
   order by p.id
   for update;

  perform pg_advisory_xact_lock(hashtext('pth_liquidar_deuda_sistema'));

  if exists (select 1 from public.deuda_sistema_detalle where estado='incidencia') then
    raise exception 'Existen incidencias contables pendientes; no se puede liquidar';
  end if;

  perform 1 from public.deuda_sistema_detalle where estado='pendiente' for update;
  select coalesce(sum(tarifa_total),0),count(distinct pedido_id),count(*)
    into v_total,v_pedidos,v_lineas
    from public.deuda_sistema_detalle
   where estado='pendiente';
  if v_lineas = 0 then raise exception 'No existe deuda pendiente para liquidar'; end if;

  select coalesce((select nombre from public.gestores where id=p_admin_id),'Ángel (Dueño)') into v_admin;
  insert into public.liquidaciones_sistema(total,pedidos_count,lineas_count,admin_id,admin_nombre,referencia)
  values(v_total,v_pedidos,v_lineas,p_admin_id,v_admin,nullif(trim(p_referencia),'')) returning id into v_id;

  insert into public.liquidaciones_sistema_detalle(liquidacion_id,deuda_detalle_id,pedido_id,tarifa_total)
  select v_id,id,pedido_id,tarifa_total from public.deuda_sistema_detalle where estado='pendiente';

  update public.deuda_sistema_detalle
     set estado='liquidado',liquidacion_id=v_id,liquidado_en=now()
   where estado='pendiente';

  update public.pedidos p set pago_sistema='Pagado'
   where exists (
     select 1 from public.liquidaciones_sistema_detalle ld
     where ld.liquidacion_id=v_id and ld.pedido_id=p.id
   );

  return jsonb_build_object('id',v_id,'total',v_total,'pedidos',v_pedidos,'lineas',v_lineas);
end;
$function$;

-- La reconstrucción histórica mantiene intactos los pedidos ya pagados.
-- Casos de control esperados: CA-1247 = $3.00 y CA-1324 = $1.00.
select public.reconstruir_deuda_sistema_pendiente();
select public.validar_deuda_sistema_integridad();

create or replace function public.notify_telegram_on_delivery()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, net, vault, pg_temp
as $function$
declare
  bot_token text;
  chat_id text;
  mensaje text;
  comision_mia_actual numeric := 0;
  tarifa_sistema_actual numeric := 0;
  total_mis_ventas numeric := 0;
  total_sistema numeric := 0;
  gran_total numeric := 0;
  gestor_limpio text;
begin
  if new.estado = 'Entregado' and old.estado is distinct from 'Entregado' then
    perform pg_advisory_xact_lock(hashtext('pth_telegram_financial_totals'));
    perform public.materializar_deuda_sistema_pedido(new.id);

    select
      max(decrypted_secret) filter (where name='telegram_bot_token'),
      max(decrypted_secret) filter (where name='telegram_chat_id')
      into bot_token,chat_id
      from vault.decrypted_secrets
      where name in ('telegram_bot_token','telegram_chat_id');
    if bot_token is null or chat_id is null then
      raise warning 'Faltan telegram_bot_token o telegram_chat_id en Supabase Vault';
      return new;
    end if;

    gestor_limpio := lower(trim(coalesce(new.gestor,'')));
    select coalesce(sum(d.tarifa_total),0) into tarifa_sistema_actual
      from public.deuda_sistema_detalle d where d.pedido_id=new.id and d.estado='pendiente';
    select coalesce(sum(d.tarifa_total),0) into total_sistema
      from public.deuda_sistema_detalle d where d.estado='pendiente';
    select coalesce(sum(p.comision_total),0) into total_mis_ventas
      from public.pedidos p
      where p.estado='Entregado' and lower(trim(p.gestor)) like '%marcel%'
        and coalesce(lower(trim(p.pago_gestor)),'pendiente') <> 'pagado';
    if gestor_limpio like '%marcel%' then comision_mia_actual := coalesce(new.comision_total,0); end if;
    gran_total := total_sistema + total_mis_ventas;

    if gestor_limpio like '%marcel%' then
      mensaje := '✅ *¡VENTA PROPIA ENTREGADA!* 🤑' || chr(10) || chr(10)
        || '📦 *Equipo:* ' || new.producto || chr(10)
        || '💰 *Comisión:* +$' || comision_mia_actual || ' USD' || chr(10)
        || '⚙️ *Tarifa Sist.:* +$' || tarifa_sistema_actual || ' USD';
    else
      mensaje := '🔔 *INGRESO DEL SISTEMA* 💻' || chr(10) || chr(10)
        || 'El gestor *' || new.gestor || '* entregó un pedido.' || chr(10)
        || '📦 *Equipo:* ' || new.producto || chr(10)
        || '⚙️ *Tu Tarifa:* +$' || tarifa_sistema_actual || ' USD';
    end if;
    mensaje := mensaje || chr(10) || chr(10)
      || '🏦 *BÓVEDA ACTUALIZADA* 🏦' || chr(10)
      || '⚙️ Deuda del sistema: *$' || total_sistema || ' USD*' || chr(10)
      || '💰 Comisiones pendientes de Marcel: *$' || total_mis_ventas || ' USD*' || chr(10)
      || '🧾 Total combinado: *$' || gran_total || ' USD*';
    perform net.http_post(
      url := 'https://api.telegram.org/bot' || bot_token || '/sendMessage',
      headers := '{"Content-Type":"application/json"}'::jsonb,
      body := jsonb_build_object('chat_id',chat_id,'text',mensaje,'parse_mode','Markdown')
    );
  end if;
  return new;
end;
$function$;

revoke all on function public.tarifa_sistema_por_unidad(numeric) from public, anon, authenticated;
revoke all on function public.materializar_deuda_sistema_pedido(uuid) from public, anon, authenticated;
revoke all on function public.reconstruir_deuda_sistema_pendiente() from public, anon, authenticated;
revoke all on function public.listar_deuda_sistema(uuid,text) from public, anon, authenticated;
revoke all on function public.resumen_deuda_sistema(uuid,text) from public, anon, authenticated;
revoke all on function public.liquidar_deuda_sistema(uuid,text,text) from public, anon, authenticated;
revoke all on function public.validar_deuda_sistema_integridad() from public, anon, authenticated;
grant execute on function public.listar_deuda_sistema(uuid,text) to anon, authenticated;
grant execute on function public.resumen_deuda_sistema(uuid,text) to anon, authenticated;
grant execute on function public.liquidar_deuda_sistema(uuid,text,text) to anon, authenticated;

commit;
